version: '3'
services:
  database:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./tmp/database/postgresql:/var/lib/postgresql/data

  schola:
    image: ruby:3.1.4
    user: 1000:1000
    working_dir: /app
    tty: true
    environment:
      - BUNDLE_PATH=/app/bundle
      - DB_HOST=database
      - RUBOCOP_CACHE_ROOT=./.cache
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: ["bash", "-c", "-l", "/app/scripts/start"]
    external_links:
      - database
    depends_on:
      - database
